### ISSUE TITLE
error CS0106: The modifier 'static' is not valid for this item

### ISSUE THREAD

**Issue by PlayCreatively** [SolidAlloy/SolidUtilities#1]
Assets\Plugins\SolidUtilities-master\Runtime\Extensions\TypeExtensions.cs(140,13): error CS0106: The modifier 'static' is not valid for this item

**Comment by SolidAlloy** [comment]
Sorry, totally forgot static local methods are only available in C#8. I removed the static modifier, please try using the latest package release:
https://github.com/SolidAlloy/SolidUtilities/releases/tag/1.7.1
https://github.com/SolidAlloy/ClassTypeReference-for-Unity/releases/tag/2.3.1
