### ISSUE TITLE
Commit broke the Type Reference package

### ISSUE THREAD

**Issue by KrzysztofPlawski1** [SolidAlloy/SolidUtilities#2]
I explained the issue in a commit comment :)

Link to the commit comment: https://github.com/SolidAlloy/SolidUtilities/commit/20f53a609bd2870b8c9c2cf4bc9983858f3c2dda#commitcomment-43756208

Keep up the great work!

**Comment by SolidAlloy** [comment]
Ah, sorry about that. I was working in another branch in ClassTypeReference and didn't merge the changes to master, that why the dependency broke. I've now merged the changes, so the error should be gone. Thanks for the report!

**Comment by KrzysztofPlawski1** [comment]
Perfect, thanks!
