### ISSUE TITLE
The variable TriangleRight of EditorIconsDatabase doesn't exist anymore.

### ISSUE THREAD

**Issue by PlayCreatively** [SolidAlloy/SolidUtilities#3]
Error: MissingReferenceException: The variable TriangleRight of EditorIconsDatabase doesn't exist anymore.
You probably need to reassign the TriangleRight variable of the 'EditorIconsDatabase' script in the inspector.

Regularly get this error and I don't know why Unity forgets the value of these variables.
However this time it doesn't help assigning the variables. I still get the error.
This is how I assigned the variables:
![image](https://user-images.githubusercontent.com/35407590/98306583-08fc5780-1fbc-11eb-85b2-c571c958a2d2.png)

I'm using the Generic ScriptableObjects repo and get the errror when trying to create a generic SO using the context menu.

**Comment by SolidAlloy** [comment]
That's odd. EditorIconsDatabase is used to display triangle icons in the type drop-down menu. A lot of people use it in [ClassTypeReference](https://github.com/SolidAlloy/ClassTypeReference-for-Unity) and didn't report such an issue. I'll think if I can get rid of these serialized references altogether and just hard-code the icons in the script. Meanwhile, could you tell me what version of Unity you are using? And how did you install GenericScriptableObjects: via OpenUPM or by installing three packages one-by-one through Package Manager?

**Comment by SolidAlloy** [comment]
I see you tried to assign a triangle icon in the MonoScript asset, but there is a separate ScriptableObject asset in the same folder that holds those references. See the screenshot:
![Screenshot 2020-11-06 120820](https://user-images.githubusercontent.com/22909454/98354182-0ab03480-2029-11eb-9fb9-f13d643dddac.png)

The "Triangle Right" icon is located in the same EditorIconsRelated folder. You can try drag-n-drop it to the "EditorIcons Database" asset if Unity somehow lost the reference. I will investigate how Unity can lose a reference in the first place.

**Comment by PlayCreatively** [comment]
Sorry for the late response. 

I'm using the repo by downloading it and just dragging it into Unity.

I didn't know the error was referring to a SO. I just threw "EditorIconsDatabase" into the search bar and the script was the only thing that came up. Only when adding the spaces in between does the SO appear.

However I can't assign the "triangle_right_16.png" to the variable. Unity also prints this error when I try to edit it:
Could not create asset from Assets/Plugins/SolidUtilities-master/Editor/EditorIconsRelated/triangle_right_16.png: File could not be read

I'm unable to make other programs recognize the file either. I think the file is just broken.

**Comment by SolidAlloy** [comment]
Thanks for checking. I googled the "File could not be read" issue and there are a lot of complaints about the incompatibility of PNG files created on Windows and OSX. I made this PNG on Windows. Do you perhaps use OSX?
Anyway, I re-exported the file using Photoshop. Could you replace triangle_right_16.png in your Unity project with the attached image? If it works, I will replace the image in the repo too.
Attached image: ![triangle_right_16](https://user-images.githubusercontent.com/22909454/98481945-b793d880-2206-11eb-8de0-2929c67887fe.png)

**Comment by PlayCreatively** [comment]
No I'm actually using windows 10 so I don't know what could have been the problem 🤔
Tried it and it works 👍

**Comment by SolidAlloy** [comment]
Thanks for checking! I will replace the image in the repo too so others don't get this error. I hope you like the Generic ScriptableObjects package now that the error is fixed ;)
