### ISSUE TITLE
The name 'Unsafe' does not exist in the current context

### ISSUE THREAD

**Issue by StarLightShadowsX** [SolidAlloy/SolidUtilities#4]
This error happens immediately upon installing the package(at least via git URL) even in a completely new project.

> Library\PackageCache\com.solidalloy.util@ec8132ef6d\Runtime\Extensions\SpanExtensions.cs(42,46): error CS0103: The name 'Unsafe' does not exist in the current context

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting the issue. I hid the reference to `Unsafe` under a preprocessor directive, so it mustn't fail if System.Runtime.CompilerServices is not installed. I've also changed the installation instructions for TypeReferences, so issues like this shouldn't happen anymore.
